using dotnet5example.Service;
using Xunit;

namespace dotnet5example.UnitTests
{
    public class NumberSentenceServiceTests
    {
        private readonly NumberSentenceService service = new NumberSentenceService();

        [Theory]
        [InlineData(0.01, "ZERO DOLLARS AND ONE CENT")]
        [InlineData(0.10, "ZERO DOLLARS AND TEN CENTS")]
        [InlineData(0.45, "ZERO DOLLARS AND FORTY-FIVE CENTS")]
        [InlineData(1.00, "ONE DOLLAR")]
        [InlineData(100.00, "ONE HUNDRED DOLLARS")]
        [InlineData(2_384_572_395.00, "TWO BILLION, THREE HUNDRED AND EIGHTY-FOUR MILLION, FIVE HUNDRED AND SEVENTY-TWO THOUSAND AND THREE HUNDRED AND NINETY-FIVE DOLLARS")]
        [InlineData(23.33, "TWENTY-THREE DOLLARS AND THIRTY-THREE CENTS")]
        [InlineData(21_342_356.32, "TWENTY-ONE MILLION, THREE HUNDRED AND FORTY-TWO THOUSAND AND THREE HUNDRED AND FIFTY-SIX DOLLARS AND THIRTY-TWO CENTS")]
        [InlineData(1_000_000_001.00, "ONE BILLION AND ONE DOLLARS")]
        [InlineData(1_000_000_001.50, "ONE BILLION AND ONE DOLLARS AND FIFTY CENTS")]
        [InlineData(1_000_234_300_023.32, "ONE TRILLION, TWO HUNDRED AND THIRTY-FOUR MILLION, THREE HUNDRED THOUSAND AND TWENTY-THREE DOLLARS AND THIRTY-TWO CENTS")]
        [InlineData(123.45, "ONE HUNDRED AND TWENTY-THREE DOLLARS AND FORTY-FIVE CENTS")]
        [InlineData(123_123_123_123_123_000_000_000_000.00, "ONE HUNDRED AND TWENTY-THREE ARE_YOU_SERIOUSILLION, ONE HUNDRED AND TWENTY-THREE SEXTILLION, ONE HUNDRED AND TWENTY-THREE QUINTILLION, ONE HUNDRED AND TWENTY-THREE QUADRILLION, ONE HUNDRED AND TWENTY-THREE TRILLION DOLLARS")]
        public void PassingTest(decimal number, string sentence)
        {
            Assert.Equal(sentence, service.GenerateNumberSentence(number));
        }

    }
}
